[package]
name = "rust-mania"
version = "0.1.0"
authors = ["Yaron M. Minsky <yminsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nphysics2d = "0.16.0"
